# C:\Users\zero\AppData\Roaming\helix
theme = "tokyonight"

[editor]
line-number="relative"
mouse = true
shell = ["powershell"]
cursorline = true
auto-completion = true
auto-format = true
completion-trigger-len = 2
auto-info = true
true-color = true
color-modes = true
auto-save = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false 

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.indent-guides]
render = true
charecter = "|"
