"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$cmd_duration $jobs $time\
$line_break\
$character"""
add_newline = false

[directory]
style = "bold blue"
read_only = " "
truncation_length = 2
truncate_to_repo = false

[git_status]
deleted = '[ $count del ](red)'
conflicted = '[ $count conflict ](yellow)'
modified = '[* $count mod ](cyan)'
staged = '[+ $count staged ](purple)'
renamed = '[ $count renamed ](cyan)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
untracked = '[? $count untracked ](yellow)'
typechanged = '[ $count typechange ](yellow)'
format = '([$all_status $ahead_behind]($style) )'
style = "yellow"

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = "purple"

[git_branch]
# always_show_remote = true
#   
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bright-green"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"